version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8072:8080"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Distribuirani-informacioni-sistemi:/workspace
    working_dir: /workspace

volumes:
  jenkins_home:
